--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    customer: acg
  name: gino-app
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: web
  strategy: 
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: web
    spec: 
      containers: 
        - 
          image: "ginolucianorojo/kubernetesexample:0.0.1"
          name: gino-app
          ports: 
            - 
              containerPort: 8080
